name       : nv-codec-headers
version    : 9.0.18.1
release    : 2
source     :
    - https://github.com/FFmpeg/nv-codec-headers/releases/download/n9.0.18.1/nv-codec-headers-9.0.18.1.tar.gz : 6181a5dac66a6990aa3baf10a77ae677f372b9068be9ef73abfd37b73fb4c745
license    : MIT
component  : multimedia.library
summary    : Headers for Nvidia Video Codec API.
description: |
    FFmpeg version of headers required to interface with Nvidias codec APIs.
install    : |
    %make_install PREFIX='/usr'
