name       : nv-codec-headers
version    : 9.1.23.1
release    : 3
source     :
    - https://github.com/FFmpeg/nv-codec-headers/releases/download/n9.1.23.1/nv-codec-headers-9.1.23.1.tar.gz : 7a1734e586799bceb9d8dbd6406d3c274159bab18a766907e9f187b208e79d61
license    : MIT
component  : multimedia.library
summary    : Headers for Nvidia Video Codec API.
description: |
    FFmpeg version of headers required to interface with Nvidias codec APIs.
install    : |
    %make_install PREFIX='/usr'
