name       : nv-codec-headers
version    : 11.1.5.1
release    : 4
source     :
    - https://github.com/FFmpeg/nv-codec-headers/releases/download/n11.1.5.1/nv-codec-headers-11.1.5.1.tar.gz : a28cdde3ac0e9e02c2dde7a1b4de5333b4ac6148a8332ca712da243a3361a0d9
license    : MIT
component  : multimedia.library
summary    : Headers for Nvidia Video Codec API.
description: |
    FFmpeg version of headers required to interface with Nvidias codec APIs.
install    : |
    %make_install PREFIX='/usr'
