name       : nv-codec-headers
version    : 8.2.15.6
release    : 1
source     :
    - https://github.com/FFmpeg/nv-codec-headers/releases/download/n8.2.15.6/nv-codec-headers-8.2.15.6.tar.gz : 10ec7fc39ccffc08561e751a626ca2b90dfdf1a25f9dc868831fab3462629569
license    : MIT
component  : multimedia.library
summary    : Headers for Nvidia Video Codec API. 
description: |
    FFmpeg version of headers required to interface with Nvidias codec APIs.
install    : |
    %make_install PREFIX='/usr'
